# Generated by Django 5.0.7 on 2024-08-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
