# Generated by Django 5.0.7 on 2024-08-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_incidencia_estado_alter_incidencia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='checks',
            field=models.JSONField(default=dict),
        ),
    ]
